site_name: Melange

theme:
  name: mkdocs
  locale: en
  highlightjs: true
  hljs_languages:
    - ocaml

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Learn: learn.md
  - API: api.md
  - Try: try.md
  - Community: community.md

extra_css:
  - css/extra.css
